apiVersion: v1 
kind: Service
metadata:
  name: kubernetes-reverse-proxy
spec:
  selector: 
    app: reverse-proxy
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
spec:
  selector:
    matchLabels:
        app: reverse-proxy
  replicas: 2
  template: 
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
      - name: reverse-proxy
        image: reverse-proxy
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
